"""Regenerate the gh-pages landing page from whatever runs are published.

The site layout is:

    runs/<YYYY-MM-DD>_<run_id>/index.html    the combined report
    runs/<YYYY-MM-DD>_<run_id>/meta.json     status + counts
    index.html                               generated by this script

The index is always rebuilt by scanning the directory rather than being
appended to, so it stays correct after the prune workflow removes old
runs — an append-only index would keep advertising reports that no
longer exist.

Usage:
    python scripts/gh_pages_index.py <site-root>
"""

from __future__ import annotations

import html
import json
import sys
from pathlib import Path


def load_runs(site: Path) -> list[dict]:
    runs = []
    runs_dir = site / "runs"
    if not runs_dir.is_dir():
        return runs
    for d in runs_dir.iterdir():
        if not d.is_dir():
            continue
        meta_file = d / "meta.json"
        meta = {}
        if meta_file.is_file():
            try:
                meta = json.loads(meta_file.read_text(encoding="utf-8"))
            except Exception:
                meta = {}
        meta.setdefault("run_dir", d.name)
        meta.setdefault("date", d.name.split("_")[0])
        meta.setdefault("status", "unknown")
        runs.append(meta)
    runs.sort(key=lambda m: (m.get("date", ""), m.get("run_id", "")), reverse=True)
    return runs


def render(runs: list[dict]) -> str:
    if runs:
        rows = []
        for m in runs:
            ok = m.get("status") == "passed"
            colour = "#16a34a" if ok else ("#dc2626" if m.get("status") == "failed" else "#6b7280")
            label = str(m.get("status", "?")).upper()
            counts = (
                f"{m.get('passed', '?')} passed &middot; {m.get('failed', '?')} failed"
                if "passed" in m else "&mdash;"
            )
            sel = html.escape(str(m.get("selection") or "all tests"))
            rows.append(f"""
      <tr>
        <td class="c1"><a href="runs/{html.escape(m['run_dir'])}/">{html.escape(m.get('date', ''))}</a>
          <div class="sub">{sel}</div></td>
        <td class="c2">{counts}</td>
        <td class="c3"><span class="badge" style="background:{colour}">{label}</span></td>
        <td class="c4">{html.escape(str(m.get('commit', '') or ''))}
          <div class="sub">{html.escape(str(m.get('actor', '') or ''))}</div></td>
      </tr>""")
        body = f"""<table>
      <thead><tr><th>Run</th><th>Result</th><th>Status</th><th>Commit</th></tr></thead>
      <tbody>{''.join(rows)}</tbody></table>"""
    else:
        body = '<p class="empty">No runs published yet.</p>'

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>sfauto — Test Runs</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ margin:0; padding:40px 20px; font:15px/1.6 system-ui,-apple-system,sans-serif;
         background:#f8fafc; color:#0f172a; }}
  @media (prefers-color-scheme: dark) {{
    body {{ background:#0b1120; color:#e2e8f0; }}
    .card {{ background:#111827 !important; border-color:#1f2937 !important; }}
    th {{ color:#94a3b8 !important; }}
    td {{ border-color:#1f2937 !important; }}
    a {{ color:#93c5fd !important; }}
  }}
  .wrap {{ max-width:900px; margin:0 auto; }}
  h1 {{ font-size:24px; margin:0 0 4px; }}
  .lede {{ color:#64748b; margin:0 0 28px; }}
  .card {{ background:#fff; border:1px solid #e2e8f0; border-radius:12px; overflow:hidden; }}
  table {{ width:100%; border-collapse:collapse; }}
  th {{ text-align:left; font:600 12px system-ui; text-transform:uppercase;
        letter-spacing:.04em; color:#64748b; padding:14px 16px; }}
  td {{ padding:14px 16px; border-top:1px solid #e2e8f0; vertical-align:top; }}
  .sub {{ font-size:12px; color:#64748b; margin-top:2px; }}
  .badge {{ display:inline-block; padding:3px 10px; border-radius:999px;
            color:#fff; font:700 11px system-ui; }}
  .c2,.c3,.c4 {{ white-space:nowrap; }}
  .empty {{ padding:40px; text-align:center; color:#64748b; }}
  a {{ color:#1d4ed8; font-weight:600; text-decoration:none; }}
  a:hover {{ text-decoration:underline; }}
  footer {{ margin-top:24px; color:#64748b; font-size:13px; }}
</style></head>
<body><div class="wrap">
  <h1>Salesforce test runs</h1>
  <p class="lede">{len(runs)} published run{'s' if len(runs) != 1 else ''}. Newest first.</p>
  <div class="card">{body}</div>
  <footer>Each run links to a single self-contained report &mdash; screenshots,
  video and API traffic embedded, no network needed once loaded.</footer>
</div></body></html>"""


def main() -> int:
    site = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    runs = load_runs(site)
    (site / "index.html").write_text(render(runs), encoding="utf-8")
    # Stop Jekyll from swallowing files that begin with an underscore.
    (site / ".nojekyll").touch()
    print(f"index rebuilt: {len(runs)} run(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
